Models/ErrorViewModel.cs
namespace BettingApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Match.cs
using System.ComponentModel.DataAnnotations;

namespace BettingApp.Models
{
    // sports:
    /* 
     * Fotbal
     * Futsal
     * Baschet
     * Handbal
     * Volei
     * Tenis
     * Tenis de masă
     * Badminton
     * Fotbal American
     * Rugby
     * Box
     * MMA
     * Darts
     * Snooker
     * Counter:Strike
     * League of Legends
     * Dota 2
     * Valorant
     * Overwatch
    */ 
    public class Match
    {
        [Key]
        public string Id { get; set; }
        [Required]
        public string Name1 { get; set; }
        [Required]
        public string Name2 { get; set; }
        [Required]
        public decimal Cota1 { get; set; }
        public decimal? CotaX { get; set; }
        [Required]
        public decimal Cota2 { get; set; }
        [Required]
        public DateTime Date { get; set; }
        [Required]
        public string Place { get; set; }
        [Required]
        public string Sport { get; set; }
        public int? Score1 { get; set; } = null;
        public int? Score2 { get; set; } = null;
        public int? Winner { get; set; } = null;
        public int? Draw { get; set; } = null;
    }
}

Models/Methods.cs
using System.Text;

namespace BettingApp.Models
{
    public class Methods
    {
        public static string RandomString(int length)
        {
            Random random = new Random();
            string chars = "abcdefghijklmnopqrstuvwxyz0123456789";

            StringBuilder sb = new StringBuilder(length);

            for (int i = 0; i < length; i++)
            {
                sb.Append(chars[random.Next(chars.Length)]);
            }
            
            return sb.ToString();
        }

        public static string TranslateDayOfWeek(DayOfWeek day)
        {
            switch(day)
            {
                case DayOfWeek.Monday:
                    return "LUNI";
                    break;

                case DayOfWeek.Tuesday:
                    return "MAR.";
                    break;

                case DayOfWeek.Wednesday:
                    return "MIE.";
                    break;

                case DayOfWeek.Thursday:
                    return "JOI";
                    break;

                case DayOfWeek.Friday:
                    return "VIN.";
                    break;

                case DayOfWeek.Saturday:
                    return "SÂM.";
                    break;

                default:
                    return "DUM.";
                    break;
            }
        }
    }
}

Controllers/HomeController.cs
using BettingApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BettingApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/MatchController.cs
using BettingApp.Data;
using BettingApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace BettingApp.Controllers
{
    public class MatchController : Controller
    {
        private readonly EntriesDbContext _db;

        public MatchController(EntriesDbContext db)
        {
            _db = db;
        }
        
        public IActionResult Index()
        {
            IEnumerable <Match> objMatchList = _db.Matches;

            return View(objMatchList);
        }
        // GET
        public IActionResult Add()
        {
            return View();
        }
        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(Match obj)
        {
            if (ModelState.IsValid)
            {
                obj.Id = DateTime.Now.Day.ToString() + "_" + DateTime.Now.Month.ToString() + "_" + DateTime.Now.Year.ToString() + "_" + Methods.RandomString(10);
                _db.Matches.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
        
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page"; // ok
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Match/Add.cshtml
@model Match
@{
    ViewData["Title"] = "Add";
}

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Adaug&#259; meci</h2>
            <hr />
        </div>

        <div class="mb-3">
            <label asp-for="Sport">Sport</label>
            <select asp-for="Sport" class="form-control">
                <option value="">Alege sportul</option>
                <option value="Fotbal">Fotbal</option>
                <option value="Futsal">Futsal</option>
                <option value="Baschet">Baschet</option>
                <option value="Handbal">Handbal</option>
                <option value="Volei">Volei</option>
                <option value="Tenis">Tenis</option>
                <option value="Tenis de masă">Tenis de masă</option>
                <option value="Badminton">Badminton</option>
                <option value="Fotbal American">Fotbal American</option>
                <option value="Rugby">Rugby</option>
                <option value="Box">Box</option>
                <option value="MMA">MMA</option>
                <option value="Darts">Darts</option>
                <option value="Snooker">Snooker</option>
                <option value="Counter:Strike">Counter:Strike</option>
                <option value="League of Legends">League of Legends</option>
                <option value="Dota 2">Dota 2</option>
                <option value="Valorant">Valorant</option>
                <option value="Overwatch">Overwatch</option>
            </select>
            <span asp-validation-for="Sport" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Name1">Jucător/Echipă 1</label>
            <input asp-for="Name1" class="form-control" />
            <span asp-validation-for="Name1" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Name2">Jucător/Echipă 2</label>
            <input asp-for="Name2" class="form-control" />
            <span asp-validation-for="Name2" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Cota1">Cota 1</label>
            <input asp-for="Cota1" class="form-control" />
            <span asp-validation-for="Cota1" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="CotaX">Cota X</label>
            <input asp-for="CotaX" class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="Cota2">Cota 2</label>
            <input asp-for="Cota2" class="form-control" />
            <span asp-validation-for="Cota2" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Date">Data</label>
            <input asp-for="Date" class="form-control" />
            <span asp-validation-for="Date" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Place">Locul</label>
            <input asp-for="Place" class="form-control" />
            <span asp-validation-for="Place" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary" style="width:150px">Adaugă</button>

    </div>
</form>

Views/Match/Index.cshtml
@model IEnumerable<Match>
@{
    ViewData["Title"] = "Index";
}

<div class="containter p-3">
    <div class="row pt-6">
        <div class="col-6">
            <h2 class="text-primary">Meciuri</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Match" asp-action="Add" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i>&nbsp;&nbsp;Adaug&#259; meci
            </a>
        </div>
    </div>
    <br/>

    @{
        DateTime now = DateTime.Now;
        string dateDisplayed;
        string timeDisplayed;
    }

    @foreach(var obj in Model)
    {
        if (now < obj.Date && obj.Winner == null && obj.Draw == null)
        {
            var diffOfDates = obj.Date - now;

            timeDisplayed = obj.Date.ToString();
            timeDisplayed = timeDisplayed[11].ToString() + timeDisplayed[12].ToString() + timeDisplayed[13].ToString() + timeDisplayed[14].ToString() + timeDisplayed[15].ToString();

            if ((int)diffOfDates.Days < 7)
                dateDisplayed = Methods.TranslateDayOfWeek(obj.Date.DayOfWeek);
            else
                dateDisplayed = obj.Date.Day.ToString() + "." + obj.Date.Month.ToString();


            if (!(obj.Sport == "Fotbal" || obj.Sport == "Futsal" || obj.Sport == "Handbal" || obj.Sport == "Rugby"))
            {
                <table class="table" style="width:50%">
                    <thead>
                        <tr>
                            <th colspan="2">@obj.Sport</th>
                            <th>1</th>
                            <th>2</th>
                        </tr>
                    </thead>

                    <tbody>
                        <tr>
                            <td>@dateDisplayed<br/>@timeDisplayed</td>
                            <td>@obj.Name1<br>@obj.Name2</td>
                            <td>@obj.Cota1</td>
                            <td>@obj.Cota2</td>
                        </tr>
                    </tbody>
                </table>
            }
            else
            {
                <table class="table" style="width:50%">
                    <thead>
                        <tr>
                            <th colspan="2">@obj.Sport</th>
                            <th>1</th>
                            <th>X</th>
                            <th>2</th>
                        </tr>
                    </thead>

                    <tbody>
                        <tr>
                            <td>@dateDisplayed<br />@timeDisplayed</td>
                            <td>@obj.Name1<br>@obj.Name2</td>
                            <td>@obj.Cota1</td>
                            <td>@obj.CotaX</td>
                            <td>@obj.Cota2</td>
                        </tr>
                    </tbody>
                </table>
            }
        }
    }
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BettingApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BettingApp.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css" rel="stylesheet">
    <script src="https://kit.fontawesome.com/562faa5f23.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EzBet</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Match" asp-action="Index">Meciuri</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - EzBet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="https://kit.fontawesome.com/562faa5f23.js" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>